version: '3.1'
services:
  stats-server:
    container_name: stats-server
    build: ewm-stats-service/stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root


  stats-db:
    image: postgres:latest
    container_name: db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    #      - TZ=Asia/Yekaterinburg

  ewm-service:
    container_name: emw-service
    build: ewm-main-service
    ports:
      - "8080:8080"
      - "5555:5005"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-main:5432/ewm
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - STAT-SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:latest
    container_name: db-main
    expose:
      - "5432"
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    #      - TZ=Asia/Yekaterinburg

