CREATE TABLE IF NOT EXISTS category
(
    id   BIGINT generated BY DEFAULT AS identity NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_category UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT generated BY DEFAULT AS identity NOT NULL,
    name  VARCHAR(256)                            NOT NULL,
    email VARCHAR(256),
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS event
(
    id                 BIGINT generated BY DEFAULT AS identity NOT NULL,
    initiator_id       BIGINT REFERENCES users (id),
    annotation         VARCHAR(2000)                           NOT NULL,
    category_id        BIGINT references category (id),
    description        VARCHAR(7000),
    event_date         timestamp without time zone,
    created_on         timestamp without time zone,
    paid               boolean,
    participant_limit  BIGINT,
    request_moderation boolean,
    title              VARCHAR(120),
    states             VARCHAR(20),
    published_on       timestamp without time zone,
    views              BIGINT,
    confirmed_requests BIGINT,
    lat                VARCHAR(100),
    lon                VARCHAR(100),
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS request
(
    id           BIGINT generated BY DEFAULT AS identity NOT NULL,
    created      timestamp without time zone,
    event_id     BIGINT,
    requester_id BIGINT,
    status       VARCHAR(50),
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation
(
    id     BIGINT generated BY DEFAULT AS identity NOT NULL,
    title  VARCHAR(250),
    pinned boolean,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_event
(
    compilation_id BIGINT REFERENCES compilation (id),
    event_id       BIGINT REFERENCES event (id)
);

CREATE TABLE IF NOT EXISTS subscriptions
(
    id             BIGINT generated BY DEFAULT AS identity NOT NULL,
    follower_id    BIGINT REFERENCES users (id) references users (id),
    event_maker_id BIGINT REFERENCES users (id) references users (id)
);